listen_addresses = '*'
shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 64MB
maintenance_work_mem = 1GB
random_page_cost = 1.1
seq_page_cost = 1.0
max_worker_processes = 8
max_parallel_workers = 8
max_parallel_workers_per_gather = 2
jit = off
track_io_timing = on
